version: '3'
services:
  redis:
    image: redis:5.0.0-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - 6379:6379
    hostname: redis
    volumes:
      - $HOME/iafoosball/stag/redis:/var/lib/redis